INSERT INTO ominaisuudet (kuvaus) VALUES ('--');
INSERT INTO ominaisuudet (kuvaus) VALUES ('Taunt');
INSERT INTO ominaisuudet (kuvaus) VALUES ('Divine Shield');
INSERT INTO kortit (nimi, mana, hyokkays, kesto) VALUES ('River Crocolisk', 2, 2, 3);
INSERT INTO kortit (nimi, mana, hyokkays, kesto) VALUES ('Wisp', 0, 1, 1);
INSERT INTO kortit (nimi, mana, hyokkays, kesto) VALUES ('Goldshire Footman', 1, 1, 2);
INSERT INTO kortit (nimi, mana, hyokkays, kesto) VALUES ('Sunwalker', 6, 4, 5);
INSERT INTO kortinOminaisuus (korttiId, ominaisuusId) VALUES (3, 2);
INSERT INTO kortinOminaisuus (korttiId, ominaisuusId) VALUES (1, 1);
INSERT INTO kortinOminaisuus (korttiId, ominaisuusId) VALUES (2, 1);
INSERT INTO kortinOminaisuus (korttiId, ominaisuusId) VALUES (4, 2);
INSERT INTO kortinOminaisuus (korttiId, ominaisuusId) VALUES (4, 3);
INSERT INTO kayttajat (nimi, salasana) VALUES ('admin', 'admin');
INSERT INTO kayttajat (nimi, salasana) VALUES ('trolli', 'trolli');
